### ISSUE TITLE
Doubts

### ISSUE THREAD

**Issue by immadhavv** [Winters123/OverWatch#1]
Hi @Winters123 , This is such a neat and impressive project on DDOS detection and I really appreciate you putting up the code online.  I'm trying to replicate Overwatch as a matter of fact and I need to clear some of my doubts.

1. Is this the official Overwatch Lightweight flow monitoring algorithm implementation, or is this your version of the algorithm implementation after reading the paper(https://www.researchgate.net/publication/322688663_OverWatch_A_Cross-Plane_DDoS_Attack_Defense_Framework_with_Collaborative_Intelligence_in_SDN) 
2. Why is lambda value a constant, 1/N ? Won't that make this a Simple Moving Average? Recent data must hold more weightage in Weighted Moving Average right?
3. getmean() function just calculates the sum of the Queue values and doesn't even return those values? Is that how its supposed to be?
4. Why is metrics data being copied to metrics_f_data before passing it the value from getmean()? Isn't it redundant?
5. Is the calculation used to find predict data and R data, right? 
- Predict data is calculated as (sum of continuous difference of values in queue * lambda)/lambda + last value
- R data is calculated as mod(actual value- predicted value/meanofthevaluesinqueue)  But the value in the numerator is actually the sum of the values in the queue according to the code?
6. I understood the training/initialization part. But during testing, you've pushed the new metrics value on to the queue and then found predict data. It seems pretty wrong to me. The new metrics is supposed to be pushed on to the queue after calculating the predict value using past data right?
7. The paper says "if each 𝑅predict is out of the (𝑅𝑙, 𝑅𝑢) range then Trigger alert to controller;" but you've turned on attack flag even if any one of the metrics is out of the range?
8. A and V variables aren't really used in the code anywhere?

Can you please give me some clarity on these doubts? It'll be really helpful. 
Sorry if it is too much though.
Also, if I'm right on any of these doubts, please let me do a pull request. :)

**Comment by Winters123** [comment]
First of all, thanks for noticing this repo! Didn't expect it since it was just a random (and silly) piece of code (should have been deleted) to try to learn how to use github :).  As it has been quite a long time and I moved to the UK and switched my work to FPGA since then, I'll try my best to give my personal answers to your questions. And you are most welcome to work on this 0.5th version if you like!
 
1. Is this the official Overwatch Lightweight flow monitoring algorithm implementation, or is this your version of the algorithm implementation after reading the paper(https://www.researchgate.net/publication/322688663_OverWatch_A_Cross-Plane_DDoS_Attack_Defense_Framework_with_Collaborative_Intelligence_in_SDN)

- No. This was one of the exercises before I started the Globecom paper (`SDN-based DDoS Attack Detection with Cross-Plane
Collaboration and Lightweight Flow Monitoring`). As you can see, the code was rough and I commented out lots of lines as I was trying to test on any kind of parameters/models on my mind. Thus, this repo didn't follow that paper in lots of details. Also bear in mind that this code obtains the counter values from linux drivers. If you want to use this on a different switch, you need to make sure what kind of APIs should you use.  

2. Why is lambda value a constant, 1/N ? Won't that make this a Simple Moving Average? Recent data must hold more weightage in Weighted Moving Average right?

- As I mentioned before, I was trying to use as many different parameters as I could to compare those results. And I believe you can try yours as well. There is a lot to explore and I don't think the parameters the paper chose are the best :)

3. `getmean()` function just calculates the sum of the Queue values and doesn't even return those values? Is that how its supposed to be?

That was wrong. Thanks for bringing this up and can you correct it since I've sent you a contribution invitation to this repo? 

3. Why is metrics data being copied to metrics_f_data before passing it the value from `getmean()`? Isn't it redundant?
Is the calculation used to find predict data and R data, right?

-Youre right. It was redundant. So feel free to delete it.

4. Predict data is calculated as (sum of continuous difference of values in queue * lambda)/lambda + last value
R data is calculated as mod(actual value- predicted value/meanofthevaluesinqueue) But the value in the numerator is actually the sum of the values in the queue according to the code?

- Again, I remember I tried methods like mod, radio, etc. to determine the **R**. Not sure what did I use in this code. But feel free to change it!

6. I understood the training/initialization part. But during testing, you've pushed the new metrics value on to the queue and then found predict data. It seems pretty wrong to me. The new metrics is supposed to be pushed on to the queue after calculating the predict value using past data right?

- 

7. The paper says "if each 𝑅predict is out of the (𝑅𝑙, 𝑅𝑢) range then Trigger alert to controller;" but you've turned on attack flag even if any one of the metrics is out of the range?

- Guess what I said above has answered your 1st part of this question right? And I still remember during our test with different kinds of DDoS traffic being fed, it was really tricky to decide when to trigger the controller. If we trigger the controller when all the R values are **all abnormal**, the detection will lose some agility; the other direction would cause we may treat normal traffic as DDoS attacks if you see what I mean. I really hope you can share some of your thoughts on this. 

8. A and V variables aren't really used in the code anywhere?

- Sorry for the confusion caused! I wouldn't be surprised if there were more variables that weren't used by `main()`! 

I've sent you an invitation to this repo so you can use this as your base code if you want. Sorry I couldn't offer more help as I had a bad habit of maintaining everything back then. 

Aagin, even I'm not working on this anymore, I'm open to discussions as long as they are related :)

**Comment by immadhavv** [comment]
Thanks for the collaboration invite. :) I'm so new to GitHub and this means a lot!
Thank God you didn't delete this!! I'd have been stuck trying to implement a wrong version of overwatch. 
Also, thanks for such a detailed response. 'I' didn't expect that.

So, basically I'm trying to implement Overwatch and use that as the base paper to compare my new work. So, I'm trying to implement it exactly as per the paper says. I've got my doubts cleared for qs 1,3,4,8 and even 2,6 and 7 as well. 

Regarding the decision to trigger the controller, I understand what you are saying. it might result in a lot of true negatives if you need all 4 of the metrics to be triggered at the same time. Maybe some k adjacent triggers of any of the 4 metrics could be used to trigger the controller if that makes sense?

I've corrected some parts of the code. :) 
(2)Changed lambda array to give the recent data more weights while still holding the criteria that sum of the lambda values=1.
(6)swapped the order of predict and metrics enqueue.
(7)attack is made to be detected only when all 4 metrics are out of range.
Hope I didn't mess up your code.

But I'm struggling with the part where you predicted the next value and calculated R value.  it'd be really nice if you can explain just those parts. according to the paper, this is the algo you've used.
![Screenshot (407)](https://user-images.githubusercontent.com/33183357/87447457-422d4800-c618-11ea-9f12-e89f99f1f189.png)

While,
the code you've used to predict is 
>for(j=0; j<N-1; j++){
		tmp[0] += lamda[j]*(metrics_tmp->data[j+1][0]-metrics_tmp->data[j][0]);
		tmp[1] += lamda[j]*(metrics_tmp->data[j+1][1]-metrics_tmp->data[j][1]);
		tmp[2] += lamda[j]*(metrics_tmp->data[j+1][2]-metrics_tmp->data[j][2]);
		tmp[3] += lamda[j]*(metrics_tmp->data[j+1][3]-metrics_tmp->data[j][3]);
	}
	predic_value[0] = metrics_tmp->data[N-1][0]+tmp[0]/(lamda[N-1]);
	predic_value[1] = metrics_tmp->data[N-1][1]+tmp[1]/(lamda[N-1]);
	predic_value[2] = metrics_tmp->data[N-1][2]+tmp[2]/(lamda[N-1]);
	predic_value[3] = metrics_tmp->data[N-1][3]+tmp[3]/(lamda[N-1]);

and the code you've used to calc R value is 
>for(i=0;i<4;i++)
R_value[i] = (predic_data[i]- metrics_data[i] )/metrics_mean_data[i]; 
and then take the mod of it. 

If I'm implementing the paper as it is, should I use the above two pieces of code, or use 
![Screenshot (406)](https://user-images.githubusercontent.com/33183357/87448305-4c037b00-c619-11ea-889c-8afc97cbf64b.png)
to predict 
and calc R value as Predictedvalue/Actualvalue?

Also is Videal just the mean of R values or does it mean something else? This has been really confusing actually.

**Comment by Winters123** [comment]
Sorry for the delayed reply. Have been in something else during the days. I think you should use `v` and calculate `R` (ratio) to do the prediction if you want to follow the paper precisely. 

1. Is Videal just the mean of R values or does it mean something else? This has been really confusing actually.
- I tried to remember the design in this paper. And I believe `v` stands for the value of the four metrics we proposed ($B$, $P$, $A_{B}$ and $A_{P}$, $B$ and $P$ will be collected just from the ingress direction). `R` is actually the ratio between two successive `V`s.

And, a tricky point of the design is (if you think about it): It doesn't really matter whether you use the Pauta criterion or not if the history is not long enough. 
Another drawback is that if the attack lasts long enough, Overwatch would treat the attack as normal traffic (Apparently).

I was once trying to extend the `history time` to solve the problems, but it would mean much more CPU resources spent on the DDoS design. And usually switches don't have a very powerful CPU. 

Would like to hear your opinion if you are interested :)

**Comment by immadhavv** [comment]
Oh, its okay. I totally understand :)

I just went through your Globecom paper regarding the overwatch algorithm and it has explained everything in detail. :) 

![Screenshot (410)](https://user-images.githubusercontent.com/33183357/87746455-428f3400-c80e-11ea-8afe-85dec8df298f.png)

So, according to this, `R is in fact the ratio of the actual value and predicted value.` That is clear.

But regarding the upper and lower bounds, it says that `avg(a)` and `std(a)` represents the average and standard deviation `OF THE n ACTUAL METRICS i.e v(a) IN THE QUEUE.` And then R function has been applied over it. 
Does that mean I've to calculate `avg(+or-)3sd` for the actual metrics and also for the predicted metrics of past n values and then take the ratio of them? 

Currently I've been taking the `avg(+or-)3sd` of the `past n Rvalues` and using them as bounds to check the current R value. (cos the Overwatch paper says that `Calculate Videal and sigma FOR THE RATIO METRIC` ) 
And it actually works. It detects when an attack is happening. I'm using only 10 as my queue size. So `history time` isn't pretty big too. But like you said, the attack was getting treated as normal traffic with time.. so then I was pushing only the normal traffic into the queues and this problem doesn't occur anymore. :)

**Comment by Winters123** [comment]
Yes. But I guess it should also be fine if you push avg(+ or -)3std directly onto `R`s. Actually, I just found the method you are using shall be better since it doesn't change the monotonicity like the method I used. 

```But like you said, the attack was getting treated as normal traffic with time.. so then I was pushing only the normal traffic into the queues and this problem doesn't occur anymore. :)```
Do you mean that every time an attack is detected, you replace the values in the queue with the normal ones?

**Comment by immadhavv** [comment]
`Yes` as in " `I've to calculate avg(+or-)3sd for the actual metrics and also for the predicted metrics of past n values and then take the ratio of them?` " this is what you have done in the paper eh? Can you please confirm that?

` Actually, I just found the method you are using shall be better since it doesn't change the monotonicity like the method I used.`
Wow. Is that so? Can you elaborate on that please? I didn't get that exactly. 

`Do you mean that every time an attack is detected, you replace the values in the queue with the normal ones?` 
No I mean ,only after confirming that it's not an attack am I pushing the values into the queue. So, all the values in the queue are normal and hence attack traffic doesn't really become the new normal.

**Comment by Winters123** [comment]
Hi Niranjan (hope I get your name right :) )

I managed some time tonight to fix the code so that it follows what was written in the paper (I hope so, cuz its too long ago). Please can you give it a try to see if it works on your side. Thanks.

1. I've to calculate avg(+or-)3sd for the actual metrics and also for the predicted metrics of past n values and then take the ratio of them? " this is what you have done in the paper eh? Can you please confirm that?

- yes. I can confirm that. I calculated `R` first and then got the `mean` and `std`, which may turn out to be not good as R was generated by division ops (the diff between actual and prediction values is magnified). I wonder changing the algo from division to substruction could do better. But if you want the method from the paper, then this is it. 

2. No I mean ,only after confirming that it's not an attack am I pushing the values into the queue. So, all the values in the queue are normal and hence attack traffic doesn't really become the new normal.
- Nice and simple, I like this idea.

**Comment by immadhavv** [comment]
Hey! You got it right!! :) I'm sorry but I'm not sure what your name is though. 

Yeah I checked the update! To my knowledge, it does follow the code precisely. :) And I already tried running my system with the same logic only(except for the lower bound in R) and it works fine. 

1.  yes. I can confirm that. I calculated R first and then got the mean and std, which may turn out to be not good as R was generated by division ops (the diff between actual and prediction values is magnified). I wonder changing the algo from division to substruction could do better. But if you want the method from the paper, then this is it.

I'm really really sorry to keep bothering you on this. But I still am not sure about this. because 

     1. your latest paper(Overwatch-2018) says `Calculate ideal value Videal and standard deviation 𝜎 FOR RATIO METRIC`.  
     2. And you were saying ` Actually, I just found the method you are using shall be better since it doesn't change the monotonicity like the method I used.` So maybe you guys updated it from (2017 paper-SDN-based DDoS Attack Detection with Cross-Plane Collaboration and Lightweight Flow Monitoring) to Overwatch(2018)? 
     3. the code you've updated now still calculates mean and sd values FROM THE R_VALUES. I feel that the code is exactly as per the Overwatch(2018) paper. If you also feel like it, don't even bother reading the above two points xD

**Comment by Winters123** [comment]
No worries. Yes, both the papers follow the same detection method on the switch part. Good luck with your work!
